### ISSUE TITLE
MineMarket 1.16.4 plugin hiba

### ISSUE THREAD

**Issue by Dmitri1277** [vngplanet/MineMarket#141]
Helló! Az 1.16.4-es Paper verziójú szerveremmel a MieMarket-Universal plugin, hibákat jelez.

> [15:48:38 ERROR]: Could not pass event InventoryCreativeEvent to MineMarket-Universal v2.94
> java.lang.NoSuchMethodError: 'java.lang.String org.bukkit.inventory.Inventory.getName()'
> 	at hu.infinityhosting.bukkit.managers.GUIManager.onCategoriesInventory(GUIManager.java:202) ~[?:?]
> 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor361.execute(Unknown Source) ~[?:?]
> 	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.4.jar:git-Paper-364]
> 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.4.jar:git-Paper-364]
> 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.4.jar:git-Paper-364]
> 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.4.jar:git-Paper-364]
> 	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2710) ~[?:git-Paper-364]
> 	at net.minecraft.server.v1_16_R3.PacketPlayInSetCreativeSlot.a(SourceFile:23) ~[patched_1.16.4.jar:git-Paper-364]
> 	at net.minecraft.server.v1_16_R3.PacketPlayInSetCreativeSlot.a(SourceFile:9) ~[patched_1.16.4.jar:git-Paper-364]
> 	at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.4.jar:git-Paper-364]
> 	at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.4.jar:git-Paper-364]
> 	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.4.jar:git-Paper-364]
> 	at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.4.jar:git-Paper-364]
> 	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.4.jar:git-Paper-364]
> 	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1133) ~[patched_1.16.4.jar:git-Paper-364]
> 	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1126) ~[patched_1.16.4.jar:git-Paper-364]
> 	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.4.jar:git-Paper-364]
> 	at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1087) ~[patched_1.16.4.jar:git-Paper-364]
> 	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1001) ~[patched_1.16.4.jar:git-Paper-364]
> 	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:178) ~[patched_1.16.4.jar:git-Paper-364]
> 	at java.lang.Thread.run(Thread.java:834) [?:?]

**Comment by markgyoni** [comment]
Nekem is van ezzel bajom!
