### ISSUE TITLE
Nem működik a MineMarket-API

### ISSUE THREAD

**Issue by andris155** [vngplanet/MineMarket#36]
```
16.07 14:19:43 [Server] WARN hu.infinityhosting.MineMarketAPI.Exceptions.NoResponseException: Az API szerver nem válaszol
16.07 14:19:43 [Server] WARN at hu.infinityhosting.MineMarketAPI.MMAPI.getXML(MMAPI.java:120)
16.07 14:19:43 [Server] WARN at hu.infinityhosting.MineMarketAPI.MMAPI.getUserCredit(MMAPI.java:397)
16.07 14:19:43 [Server] WARN at hu.Bod.Kredites.Kredites.onCMD(Kredites.java:73)
16.07 14:19:43 [Server] WARN at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor955.execute(Unknown Source)
16.07 14:19:43 [Server] WARN at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44)
16.07 14:19:43 [Server] WARN at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74)
16.07 14:19:43 [Server] WARN at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
16.07 14:19:43 [Server] WARN at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:514)
16.07 14:19:43 [Server] WARN at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:499)
16.07 14:19:43 [Server] WARN at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1416)
16.07 14:19:43 [Server] WARN at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1229)
16.07 14:19:43 [Server] WARN at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
16.07 14:19:43 [Server] WARN at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:5)
16.07 14:19:43 [Server] WARN at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14)
16.07 14:19:43 [Server] WARN at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
16.07 14:19:43 [Server] WARN at java.util.concurrent.FutureTask.run(FutureTask.java:266)
16.07 14:19:43 [Server] WARN at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
16.07 14:19:43 [Server] WARN at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:842)
16.07 14:19:43 [Server] WARN at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423)
16.07 14:19:43 [Server] WARN at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:766)
16.07 14:19:43 [Server] WARN at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:664)
16.07 14:19:43 [Server] WARN at java.lang.Thread.run(Thread.java:748)
```

**Comment by vngplanet** [comment]
Próbáljátok meg https helyett http protokollal, ugyanis jelenleg átalakítás miatt ki van kapcsolva a SSL/TSL titkosítás.

**Comment by vngplanet** [comment]
https://i.gyazo.com/47056cbf830ed86d362bdc1c5eaeba22.png

https://i.gyazo.com/c2b7dcacb870d1a556f4aaf45b462829.png
