### ISSUE TITLE
Egyre többször nem éri el a szerver a MineMarket-et

### ISSUE THREAD

**Issue by andris155** [vngplanet/MineMarket#64]
```
[10:23:13] [Craft Scheduler Thread - 949/WARN]: java.util.concurrent.ExecutionException: java.net.SocketTimeoutException: Read timed out
[10:23:13] [Craft Scheduler Thread - 949/WARN]: 	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
[10:23:13] [Craft Scheduler Thread - 949/WARN]: 	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
[10:23:13] [Craft Scheduler Thread - 949/WARN]: 	at hu.infinityhosting.bukkit.managers.PurchaseManager$PurchaseProcessor$1.run(PurchaseManager.java:134)
[10:23:13] [Craft Scheduler Thread - 949/WARN]: 	at org.bukkit.craftbukkit.v1_13_R1.scheduler.CraftTask.run(CraftTask.java:63)
[10:23:13] [Craft Scheduler Thread - 949/WARN]: 	at org.bukkit.craftbukkit.v1_13_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[10:23:13] [Craft Scheduler Thread - 949/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[10:23:13] [Craft Scheduler Thread - 949/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[10:23:13] [Craft Scheduler Thread - 949/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[10:23:13] [Craft Scheduler Thread - 949/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[10:23:13] [Craft Scheduler Thread - 949/WARN]: Caused by: java.net.SocketTimeoutException: Read timed out
[10:23:13] [Craft Scheduler Thread - 949/WARN]: 	at java.net.SocketInputStream.socketRead0(Native Method)
[10:23:13] [Craft Scheduler Thread - 949/WARN]: 	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
[10:23:13] [Craft Scheduler Thread - 949/WARN]: 	at java.net.SocketInputStream.read(SocketInputStream.java:171)
[10:23:13] [Craft Scheduler Thread - 949/WARN]: 	at java.net.SocketInputStream.read(SocketInputStream.java:141)
[10:23:13] [Craft Scheduler Thread - 949/WARN]: 	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
[10:23:13] [Craft Scheduler Thread - 949/WARN]: 	at sun.security.ssl.InputRecord.read(InputRecord.java:503)
[10:23:13] [Craft Scheduler Thread - 949/WARN]: 	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:983)
[10:23:13] [Craft Scheduler Thread - 949/WARN]: 	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1385)
[10:23:13] [Craft Scheduler Thread - 949/WARN]: 	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1413)
[10:23:13] [Craft Scheduler Thread - 949/WARN]: 	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1397)
[10:23:13] [Craft Scheduler Thread - 949/WARN]: 	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
[10:23:13] [Craft Scheduler Thread - 949/WARN]: 	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
[10:23:13] [Craft Scheduler Thread - 949/WARN]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564)
[10:23:13] [Craft Scheduler Thread - 949/WARN]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
[10:23:13] [Craft Scheduler Thread - 949/WARN]: 	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263)
[10:23:13] [Craft Scheduler Thread - 949/WARN]: 	at hu.infinityhosting.common.HttpQuery.call(HttpQuery.java:79)
[10:23:13] [Craft Scheduler Thread - 949/WARN]: 	at hu.infinityhosting.common.HttpQuery.call(HttpQuery.java:1)
[10:23:13] [Craft Scheduler Thread - 949/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[10:23:13] [Craft Scheduler Thread - 949/WARN]: 	... 3 more
```

**Comment by PlayS24** [comment]
Halihó! Megjavítottam a MineMarket pluginját, hogy működjön a legújabb szerver/java verziókon! Remélem segíteni tudtam ezzel pár embernek. Letöltési link: https://www.spigotmc.org/resources/minemarket-plugin-fixed-version-1-7x-1-16x.84842/
